apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: log-pipeline
type: Opaque
stringData:
  mysql-root-password: "rootpass1234"
  mysql-database: "appdb"
  mysql-user: "appuser"
  mysql-password: "apppass1234"
